---
#==============================================================================
# Base installation
#==============================================================================


#------------------------------
# db-*
#------------------------------
- hosts: "db-*"
  tasks:
    - name: Install system packages
      apt: name={{ item }} state=present
      with_items:
        - postgresql
        - libpq-dev
        - python-pip
        - python-dev
    - name: Install python packages
      pip: name={{ item }}
      with_items:
        - psycopg2
    - service: name=postgresql state=started

#------------------------------
# db-secret
#------------------------------
- hosts: db-secret
  sudo: yes
  sudo_user: postgres
  tasks:
    - postgresql_db: name=secret
    - postgresql_user: name=secret
                       db=secret
                       password=secret
    - postgresql_privs: >
        db=secret
        roles=secret
        privs=ALL
        objs=ALL_IN_SCHEMA

#------------------------------
# db-app
#------------------------------
- hosts: db-app
  sudo: yes
  sudo_user: postgres
  tasks:
    - postgresql_db: name=app
    - postgresql_user: name=app
                       db=app
                       password=app
    - postgresql_privs: >
        db=app
        roles=app
        privs=ALL
        objs=ALL_IN_SCHEMA

#------------------------------
# rabbit
#------------------------------
- hosts: rabbit
  tasks:
    - apt: name=rabbitmq-server
    - service: name=rabbitmq-server state=started


#------------------------------
# worker
#------------------------------
- hosts: worker
  tasks:
    - name: worker user
      user: name=worker
            comment="Bank Access Worker"
            append=yes
            home=/home/worker
    # XXX I don't like manually keeping this up to date from the Dockerfile
    # in the bank-access repo.  Perhaps I'll convert the Dockerfile to an
    # ansible role.
    - name: Install system packages
      apt: name={{ item }} state=present
      with_items:
        - python-dev
        - python-virtualenv
        - build-essential
        - git
        - libsqlite3-dev
        - curl
        - libz-dev
        - libxml2-dev
        - libxslt1-dev
        - x11vnc
        - xvfb
        - firefox
        - xfonts-100dpi
        - xfonts-75dpi
        - xfonts-scalable
        - xfonts-cyrillic

    # Xvfb
    - name: Init xvfb
      copy: dest=/etc/init.d/xvfb
            src=util/xvfb.init.d
            mode=u+x
    - name: Start xvfb
      service: name=xvfb state=started

    # x11vnc
    - file: path=/home/root/.vnc/passwd
            owner=root
            group=root
            state=directory
    - name: Configure x11vnc
      command: x11vnc -storepasswd foo /home/root/.vnc/passwd
               creates="/home/root/.vnc/passwd"
    - name: Init x11vnc
      copy: dest=/etc/init.d/x11vnc
            src=util/x11vnc.init.d
            mode=u+x
    - name: Start x11vnc
      service: name=x11vnc state=started

#==============================================================================
# Security
#==============================================================================
# - hosts: all
#   tasks:
#     - name: Firewall | install ufw 
#       apt: name=ufw state=present
#       tags: security
#     - ufw: state=enabled policy=allow
#       tags: security


#==============================================================================
# Application code
#==============================================================================
- hosts: worker
  vars:
    virtualenv: /home/worker/venv
    banka_dir: /home/worker/bank-access
  sudo: yes
  sudo_user: worker
  tasks:
    - name: Get bank-access repo
      git: repo=https://github.com/simplefin/bank-access.git
           dest={{ banka_dir }}
           version=master
    - name: Upgrade pip
      pip: virtualenv={{ virtualenv }}
           name=pip
           version=6.0.8
    - name: Upgrade python dependencies
      async: 1000
      poll: 10
      pip: virtualenv={{ virtualenv }}
           requirements={{ banka_dir }}/requirements.txt

